segrap_task001_one_hot_label_names = {
    'Brain': 1,
    "BrainStem": 2,
    "Chiasm": 3,
    "TemporalLobe_L": 4,
    "TemporalLobe_R": 5,
    "TemporalLobe_Hippocampus_OverLap_L": 6,
    "TemporalLobe_Hippocampus_OverLap_R": 7,
    "Hippocampus_L": 8,
    "Hippocampus_R": 9,
    'Eye_L': 10,
    'Eye_R': 11,
    "Lens_L": 12,
    "Lens_R": 13,
    "OpticNerve_L": 14,
    "OpticNerve_R": 15,
    "MiddleEar_L": 16,
    "MiddleEar_R": 17,
    "IAC_L": 18,
    "IAC_R": 19,
    "MiddleEar_TympanicCavity_OverLap_L": 20,
    "MiddleEar_TympanicCavity_OverLap_R": 21,
    "TympanicCavity_L": 22,
    "TympanicCavity_R": 23,
    "MiddleEar_VestibulSemi_OverLap_L": 24,
    "MiddleEar_VestibulSemi_OverLap_R": 25,
    "VestibulSemi_L": 26,
    "VestibulSemi_R": 27,
    "MiddleEar_Cochlea_OverLap_L": 28,
    "MiddleEar_Cochlea_OverLap_R": 29,
    "Cochlea_L": 30,
    "Cochlea_R": 31,
    "MiddleEar_ETbone_OverLap_L": 32,
    "MiddleEar_ETbone_OverLap_R": 33,
    "ETbone_L": 34,
    "ETbone_R": 35, "Pituitary": 36,
    "OralCavity": 37,
    "Mandible_L": 38,
    "Mandible_R": 39,
    "Submandibular_L": 40,
    "Submandibular_R": 41,
    "Parotid_L": 42,
    "Parotid_R": 43,
    "Mastoid_L": 44,
    "Mastoid_R": 45,
    "TMjoint_L": 46,
    "TMjoint_R": 47,
    "SpinalCord": 48,
    "Esophagus": 49,
    "Larynx": 50,
    "Larynx_Larynx_Glottic_OverLap": 51,
    "Larynx_Glottic": 52,
    "Larynx_Larynx_Supraglot_OverLap": 53,
    "Larynx_Supraglot": 54,
    "Larynx_PharynxConst_OverLap": 55,
    "PharynxConst": 56,
    "Thyroid": 57,
    "Trachea": 58
}

segrap_task002_one_hot_label_names = {
    "GTVp": 1,
    "GTVnd": 2}

__all__ = ['segrap_task001_one_hot_label_names', 'segrap_task002_one_hot_label_names']
